name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        exampleDir:
          - lit-typescript-vite
          - preact-typescript-vite
          - react-typescript-vite
          - svelte-typescript-vite
          - vue-typescript-vite
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
          working-directory: ${{ matrix.exampleDir }}
        - name: Test
          run: npm run wdio
          working-directory: ${{ matrix.exampleDir }}
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: ${{ matrix.exampleDir }}/test/logs
            path: ${{ matrix.exampleDir }}/test/logs
